name: SC_BedWars
version: '${version}'
main: fr.mathis_bruel.spacecube.bedwars.Main
authors: [ Mathis_Bruel ]
description: BedWars
website: https://www.spacecube.games/
depend:
  - FastAsyncWorldEdit
  - WorldEdit
  - SpaceCubeApi
  - HeadDatabase
  - Citizens
load: POSTWORLD
commands:
  test:
    aliases: test
    description: Command for test
  bedwars:
    aliases: bw
    description: Command for players
  bedwars-a:
    aliases:
      - bwa
      - bw-a
    description: Command bedwars for admins for config the plugin
    permission: bedwars.a
  spawn:
    aliases: spawn
    description: Command for spawn
permissions:
  bedwars.stats:
    description: Permet aux joueurs de voir ses stats
  bedwars.play:
    description: Permet de rejoindre une partie
  bedwars.leave:
    description: Permet de quitter une partie
  bedwars.a:
    description: Permet d'avoir la permission de la gestion du plugin
